dependencies:
- python <3.11
- spyder 6.1.7
- cython
- matplotlib
- pandas
- pillow
- scikit-learn
- scipy
- sympy
# This is required to avoid conda complaining about it.
- pip

# Required to prevent an error with ML-KEM
- cryptography >48.0.0

# Required for jupyter-desktop-server
- websockify
- nbgitpuller
- pip:
    - jupyter-desktop-server
