#!/bin/bash

set -euo pipefail

cp -r binder/Desktop ${HOME}/Desktop

# Apply our Xfce settings
mkdir -p ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml
cp binder/xsettings.xml ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/
cp binder/xfce4-panel.xml ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/

# For nbgitpuller
jupyter server extension enable --py nbgitpuller --sys-prefix

# For Spyder
mkdir -p ${HOME}/.config/spyder-py3/config
cp binder/spyder/spyder.ini ${HOME}/.config/spyder-py3/config/
